#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

ynh_config_remove_systemd

ynh_config_remove_logrotate

ynh_config_remove_nginx

ynh_nodejs_remove

#=================================================
# AUTOSYNCHRONIZED SPECIFICS
#=================================================

if [[ $autosynchronize == true ]]; then
    # Remove dato specific config added to couch
    ynh_safe_rm "/opt/couchdb/etc/local.d/$app.ini"

    # notify that couchdb users and dbs are left
    ynh_print_warn "Please note that dbs and users in the attached couchdb instance haven't been modified. If you want them removed, you should do that manually, for example from the couchdb web interface."
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
